# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/ui/DeleteProhibitionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteProhibitionWindow(object):
    def setupUi(self, DeleteProhibitionWindow):
        DeleteProhibitionWindow.setObjectName("DeleteProhibitionWindow")
        DeleteProhibitionWindow.resize(250, 100)
        DeleteProhibitionWindow.setMinimumSize(QtCore.QSize(250, 100))
        DeleteProhibitionWindow.setMaximumSize(QtCore.QSize(250, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DeleteProhibitionWindow.setWindowIcon(icon)
        DeleteProhibitionWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.label_4 = QtWidgets.QLabel(DeleteProhibitionWindow)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.prohibition_id_spnbox = QtWidgets.QSpinBox(DeleteProhibitionWindow)
        self.prohibition_id_spnbox.setGeometry(QtCore.QRect(140, 20, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prohibition_id_spnbox.setFont(font)
        self.prohibition_id_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.prohibition_id_spnbox.setMaximum(999999)
        self.prohibition_id_spnbox.setObjectName("prohibition_id_spnbox")
        self.del_prohibition_btn = QtWidgets.QPushButton(DeleteProhibitionWindow)
        self.del_prohibition_btn.setGeometry(QtCore.QRect(70, 60, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.del_prohibition_btn.setFont(font)
        self.del_prohibition_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.del_prohibition_btn.setObjectName("del_prohibition_btn")

        self.retranslateUi(DeleteProhibitionWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteProhibitionWindow)

    def retranslateUi(self, DeleteProhibitionWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteProhibitionWindow.setWindowTitle(_translate("DeleteProhibitionWindow", "Delete Prohibition"))
        self.label_4.setText(_translate("DeleteProhibitionWindow", "Prohibition ID"))
        self.del_prohibition_btn.setText(_translate("DeleteProhibitionWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteProhibitionWindow = QtWidgets.QDialog()
    ui = Ui_DeleteProhibitionWindow()
    ui.setupUi(DeleteProhibitionWindow)
    DeleteProhibitionWindow.show()
    sys.exit(app.exec_())
