# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/ui/DrugIssuingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrugIssuingWindow(object):
    def setupUi(self, DrugIssuingWindow):
        DrugIssuingWindow.setObjectName("DrugIssuingWindow")
        DrugIssuingWindow.resize(420, 220)
        DrugIssuingWindow.setMinimumSize(QtCore.QSize(420, 220))
        DrugIssuingWindow.setMaximumSize(QtCore.QSize(420, 220))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DrugIssuingWindow.setWindowIcon(icon)
        DrugIssuingWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.medic_fname_fld = QtWidgets.QLineEdit(DrugIssuingWindow)
        self.medic_fname_fld.setGeometry(QtCore.QRect(120, 40, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medic_fname_fld.setFont(font)
        self.medic_fname_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.medic_fname_fld.setMaxLength(50)
        self.medic_fname_fld.setObjectName("medic_fname_fld")
        self.medic_lname_fld = QtWidgets.QLineEdit(DrugIssuingWindow)
        self.medic_lname_fld.setGeometry(QtCore.QRect(120, 10, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medic_lname_fld.setFont(font)
        self.medic_lname_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.medic_lname_fld.setMaxLength(50)
        self.medic_lname_fld.setObjectName("medic_lname_fld")
        self.medic_patronymic_fld = QtWidgets.QLineEdit(DrugIssuingWindow)
        self.medic_patronymic_fld.setGeometry(QtCore.QRect(120, 70, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medic_patronymic_fld.setFont(font)
        self.medic_patronymic_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.medic_patronymic_fld.setMaxLength(50)
        self.medic_patronymic_fld.setObjectName("medic_patronymic_fld")
        self.rank_cbox = QtWidgets.QComboBox(DrugIssuingWindow)
        self.rank_cbox.setGeometry(QtCore.QRect(20, 130, 381, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rank_cbox.setFont(font)
        self.rank_cbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.rank_cbox.setCurrentText("")
        self.rank_cbox.setObjectName("rank_cbox")
        self.label = QtWidgets.QLabel(DrugIssuingWindow)
        self.label.setGeometry(QtCore.QRect(20, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.datetime_editor = QtWidgets.QDateTimeEdit(DrugIssuingWindow)
        self.datetime_editor.setGeometry(QtCore.QRect(20, 185, 194, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.datetime_editor.setFont(font)
        self.datetime_editor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.datetime_editor.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 9, 14), QtCore.QTime(0, 0, 0)))
        self.datetime_editor.setObjectName("datetime_editor")
        self.label_2 = QtWidgets.QLabel(DrugIssuingWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 165, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.issue_btn = QtWidgets.QPushButton(DrugIssuingWindow)
        self.issue_btn.setGeometry(QtCore.QRect(310, 180, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.issue_btn.setFont(font)
        self.issue_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.issue_btn.setObjectName("issue_btn")
        self.quantity_spnbox = QtWidgets.QSpinBox(DrugIssuingWindow)
        self.quantity_spnbox.setGeometry(QtCore.QRect(20, 80, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantity_spnbox.setFont(font)
        self.quantity_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.quantity_spnbox.setObjectName("quantity_spnbox")
        self.label_3 = QtWidgets.QLabel(DrugIssuingWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DrugIssuingWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.drug_id_spnbox = QtWidgets.QSpinBox(DrugIssuingWindow)
        self.drug_id_spnbox.setGeometry(QtCore.QRect(20, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drug_id_spnbox.setFont(font)
        self.drug_id_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.drug_id_spnbox.setMaximum(999999)
        self.drug_id_spnbox.setObjectName("drug_id_spnbox")

        self.retranslateUi(DrugIssuingWindow)
        QtCore.QMetaObject.connectSlotsByName(DrugIssuingWindow)

    def retranslateUi(self, DrugIssuingWindow):
        _translate = QtCore.QCoreApplication.translate
        DrugIssuingWindow.setWindowTitle(_translate("DrugIssuingWindow", "Drug issuing"))
        self.medic_fname_fld.setPlaceholderText(_translate("DrugIssuingWindow", "Medic first name"))
        self.medic_lname_fld.setPlaceholderText(_translate("DrugIssuingWindow", "Medic last name"))
        self.medic_patronymic_fld.setPlaceholderText(_translate("DrugIssuingWindow", "Medic patronymic"))
        self.rank_cbox.setPlaceholderText(_translate("DrugIssuingWindow", "rank"))
        self.label.setText(_translate("DrugIssuingWindow", "Medic rank"))
        self.datetime_editor.setDisplayFormat(_translate("DrugIssuingWindow", "dd-MM-yyyy HH:mm"))
        self.label_2.setText(_translate("DrugIssuingWindow", "Date & Time"))
        self.issue_btn.setText(_translate("DrugIssuingWindow", "Issue"))
        self.label_3.setText(_translate("DrugIssuingWindow", "Quantity"))
        self.label_4.setText(_translate("DrugIssuingWindow", "Drug ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrugIssuingWindow = QtWidgets.QDialog()
    ui = Ui_DrugIssuingWindow()
    ui.setupUi(DrugIssuingWindow)
    DrugIssuingWindow.show()
    sys.exit(app.exec_())
