# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/ui/ManageDrugsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageDrugsWindow(object):
    def setupUi(self, ManageDrugsWindow):
        ManageDrugsWindow.setObjectName("ManageDrugsWindow")
        ManageDrugsWindow.resize(960, 610)
        ManageDrugsWindow.setMinimumSize(QtCore.QSize(960, 610))
        ManageDrugsWindow.setMaximumSize(QtCore.QSize(960, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ManageDrugsWindow.setWindowIcon(icon)
        ManageDrugsWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.tableWidget = QtWidgets.QTableWidget(ManageDrugsWindow)
        self.tableWidget.setGeometry(QtCore.QRect(0, 90, 960, 520))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.add_drug_btn = QtWidgets.QPushButton(ManageDrugsWindow)
        self.add_drug_btn.setGeometry(QtCore.QRect(20, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_drug_btn.setFont(font)
        self.add_drug_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_drug_btn.setObjectName("add_drug_btn")
        self.search_fld = QtWidgets.QLineEdit(ManageDrugsWindow)
        self.search_fld.setGeometry(QtCore.QRect(280, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_fld.setFont(font)
        self.search_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.search_fld.setObjectName("search_fld")
        self.search_btn = QtWidgets.QPushButton(ManageDrugsWindow)
        self.search_btn.setGeometry(QtCore.QRect(750, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.refresh_btn = QtWidgets.QPushButton(ManageDrugsWindow)
        self.refresh_btn.setGeometry(QtCore.QRect(850, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.refresh_btn.setObjectName("refresh_btn")
        self.issue_drug_btn = QtWidgets.QPushButton(ManageDrugsWindow)
        self.issue_drug_btn.setGeometry(QtCore.QRect(120, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.issue_drug_btn.setFont(font)
        self.issue_drug_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.issue_drug_btn.setObjectName("issue_drug_btn")
        self.update_drug_btn = QtWidgets.QPushButton(ManageDrugsWindow)
        self.update_drug_btn.setGeometry(QtCore.QRect(20, 50, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update_drug_btn.setFont(font)
        self.update_drug_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.update_drug_btn.setObjectName("update_drug_btn")
        self.drug_atc = QtWidgets.QLineEdit(ManageDrugsWindow)
        self.drug_atc.setGeometry(QtCore.QRect(660, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drug_atc.setFont(font)
        self.drug_atc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.drug_atc.setInputMask("")
        self.drug_atc.setMaxLength(7)
        self.drug_atc.setObjectName("drug_atc")

        self.retranslateUi(ManageDrugsWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageDrugsWindow)

    def retranslateUi(self, ManageDrugsWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageDrugsWindow.setWindowTitle(_translate("ManageDrugsWindow", "Manage Drugs"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ManageDrugsWindow", "Drug ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ManageDrugsWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ManageDrugsWindow", "ATC-code"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ManageDrugsWindow", "Quantity"))
        self.add_drug_btn.setText(_translate("ManageDrugsWindow", "Add drug"))
        self.search_fld.setPlaceholderText(_translate("ManageDrugsWindow", "Drug name"))
        self.search_btn.setText(_translate("ManageDrugsWindow", "Search"))
        self.refresh_btn.setText(_translate("ManageDrugsWindow", "Refresh"))
        self.issue_drug_btn.setText(_translate("ManageDrugsWindow", "To issue"))
        self.update_drug_btn.setText(_translate("ManageDrugsWindow", "Update drug"))
        self.drug_atc.setPlaceholderText(_translate("ManageDrugsWindow", "atc code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageDrugsWindow = QtWidgets.QDialog()
    ui = Ui_ManageDrugsWindow()
    ui.setupUi(ManageDrugsWindow)
    ManageDrugsWindow.show()
    sys.exit(app.exec_())
