# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/ui/SupplierUpdatingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SupplierUpdatingWindow(object):
    def setupUi(self, SupplierUpdatingWindow):
        SupplierUpdatingWindow.setObjectName("SupplierUpdatingWindow")
        SupplierUpdatingWindow.resize(550, 350)
        SupplierUpdatingWindow.setMinimumSize(QtCore.QSize(550, 350))
        SupplierUpdatingWindow.setMaximumSize(QtCore.QSize(550, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SupplierUpdatingWindow.setWindowIcon(icon)
        SupplierUpdatingWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.supplier_id_spnbox = QtWidgets.QSpinBox(SupplierUpdatingWindow)
        self.supplier_id_spnbox.setGeometry(QtCore.QRect(170, 10, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.supplier_id_spnbox.setFont(font)
        self.supplier_id_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.supplier_id_spnbox.setMaximum(999999)
        self.supplier_id_spnbox.setObjectName("supplier_id_spnbox")
        self.update_supplier_btn = QtWidgets.QPushButton(SupplierUpdatingWindow)
        self.update_supplier_btn.setGeometry(QtCore.QRect(440, 310, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update_supplier_btn.setFont(font)
        self.update_supplier_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.update_supplier_btn.setObjectName("update_supplier_btn")
        self.label_4 = QtWidgets.QLabel(SupplierUpdatingWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(SupplierUpdatingWindow)
        self.line.setGeometry(QtCore.QRect(20, 30, 321, 16))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.get_data_supplier_btn = QtWidgets.QPushButton(SupplierUpdatingWindow)
        self.get_data_supplier_btn.setGeometry(QtCore.QRect(260, 10, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.get_data_supplier_btn.setFont(font)
        self.get_data_supplier_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.get_data_supplier_btn.setObjectName("get_data_supplier_btn")
        self.contact_info_fld = QtWidgets.QPlainTextEdit(SupplierUpdatingWindow)
        self.contact_info_fld.setGeometry(QtCore.QRect(20, 120, 511, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contact_info_fld.setFont(font)
        self.contact_info_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.contact_info_fld.setMaximumBlockCount(0)
        self.contact_info_fld.setBackgroundVisible(False)
        self.contact_info_fld.setObjectName("contact_info_fld")
        self.country_fld = QtWidgets.QLineEdit(SupplierUpdatingWindow)
        self.country_fld.setGeometry(QtCore.QRect(20, 80, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.country_fld.setFont(font)
        self.country_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.country_fld.setMaxLength(200)
        self.country_fld.setObjectName("country_fld")
        self.supplier_name_fld = QtWidgets.QLineEdit(SupplierUpdatingWindow)
        self.supplier_name_fld.setGeometry(QtCore.QRect(20, 50, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.supplier_name_fld.setFont(font)
        self.supplier_name_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.supplier_name_fld.setMaxLength(200)
        self.supplier_name_fld.setObjectName("supplier_name_fld")

        self.retranslateUi(SupplierUpdatingWindow)
        QtCore.QMetaObject.connectSlotsByName(SupplierUpdatingWindow)

    def retranslateUi(self, SupplierUpdatingWindow):
        _translate = QtCore.QCoreApplication.translate
        SupplierUpdatingWindow.setWindowTitle(_translate("SupplierUpdatingWindow", "Supplier Updating"))
        self.update_supplier_btn.setText(_translate("SupplierUpdatingWindow", "Update"))
        self.label_4.setText(_translate("SupplierUpdatingWindow", "Supplier ID"))
        self.get_data_supplier_btn.setText(_translate("SupplierUpdatingWindow", "Load info"))
        self.contact_info_fld.setPlaceholderText(_translate("SupplierUpdatingWindow", "Contact info"))
        self.country_fld.setPlaceholderText(_translate("SupplierUpdatingWindow", "Country"))
        self.supplier_name_fld.setPlaceholderText(_translate("SupplierUpdatingWindow", "Supplier name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SupplierUpdatingWindow = QtWidgets.QDialog()
    ui = Ui_SupplierUpdatingWindow()
    ui.setupUi(SupplierUpdatingWindow)
    SupplierUpdatingWindow.show()
    sys.exit(app.exec_())
