# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/DrugUpdatingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrugUpdatingWindow(object):
    def setupUi(self, DrugUpdatingWindow):
        DrugUpdatingWindow.setObjectName("DrugUpdatingWindow")
        DrugUpdatingWindow.resize(550, 350)
        DrugUpdatingWindow.setMinimumSize(QtCore.QSize(550, 350))
        DrugUpdatingWindow.setMaximumSize(QtCore.QSize(550, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DrugUpdatingWindow.setWindowIcon(icon)
        DrugUpdatingWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.label_4 = QtWidgets.QLabel(DrugUpdatingWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.drug_id_spnbox = QtWidgets.QSpinBox(DrugUpdatingWindow)
        self.drug_id_spnbox.setGeometry(QtCore.QRect(100, 10, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drug_id_spnbox.setFont(font)
        self.drug_id_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.drug_id_spnbox.setMaximum(999999)
        self.drug_id_spnbox.setObjectName("drug_id_spnbox")
        self.label_3 = QtWidgets.QLabel(DrugUpdatingWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.quantity_spnbox = QtWidgets.QSpinBox(DrugUpdatingWindow)
        self.quantity_spnbox.setGeometry(QtCore.QRect(100, 80, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantity_spnbox.setFont(font)
        self.quantity_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.quantity_spnbox.setObjectName("quantity_spnbox")
        self.drug_description_fld = QtWidgets.QPlainTextEdit(DrugUpdatingWindow)
        self.drug_description_fld.setGeometry(QtCore.QRect(20, 110, 511, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drug_description_fld.setFont(font)
        self.drug_description_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.drug_description_fld.setMaximumBlockCount(0)
        self.drug_description_fld.setBackgroundVisible(False)
        self.drug_description_fld.setObjectName("drug_description_fld")
        self.update_drug_btn = QtWidgets.QPushButton(DrugUpdatingWindow)
        self.update_drug_btn.setGeometry(QtCore.QRect(440, 310, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update_drug_btn.setFont(font)
        self.update_drug_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.update_drug_btn.setObjectName("update_drug_btn")
        self.drug_name_fld = QtWidgets.QLineEdit(DrugUpdatingWindow)
        self.drug_name_fld.setGeometry(QtCore.QRect(20, 50, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drug_name_fld.setFont(font)
        self.drug_name_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.drug_name_fld.setMaxLength(200)
        self.drug_name_fld.setObjectName("drug_name_fld")
        self.drug_atc_fld = QtWidgets.QLineEdit(DrugUpdatingWindow)
        self.drug_atc_fld.setGeometry(QtCore.QRect(190, 80, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drug_atc_fld.setFont(font)
        self.drug_atc_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.drug_atc_fld.setInputMask("")
        self.drug_atc_fld.setMaxLength(7)
        self.drug_atc_fld.setObjectName("drug_atc_fld")
        self.get_data_drug_btn = QtWidgets.QPushButton(DrugUpdatingWindow)
        self.get_data_drug_btn.setGeometry(QtCore.QRect(190, 10, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.get_data_drug_btn.setFont(font)
        self.get_data_drug_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.get_data_drug_btn.setObjectName("get_data_drug_btn")
        self.line = QtWidgets.QFrame(DrugUpdatingWindow)
        self.line.setGeometry(QtCore.QRect(20, 30, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(DrugUpdatingWindow)
        QtCore.QMetaObject.connectSlotsByName(DrugUpdatingWindow)

    def retranslateUi(self, DrugUpdatingWindow):
        _translate = QtCore.QCoreApplication.translate
        DrugUpdatingWindow.setWindowTitle(_translate("DrugUpdatingWindow", "Drug updating"))
        self.label_4.setText(_translate("DrugUpdatingWindow", "Drug ID"))
        self.label_3.setText(_translate("DrugUpdatingWindow", "Quantity"))
        self.drug_description_fld.setPlaceholderText(_translate("DrugUpdatingWindow", "description"))
        self.update_drug_btn.setText(_translate("DrugUpdatingWindow", "Update drug"))
        self.drug_name_fld.setPlaceholderText(_translate("DrugUpdatingWindow", "drug name"))
        self.drug_atc_fld.setPlaceholderText(_translate("DrugUpdatingWindow", "atc code"))
        self.get_data_drug_btn.setText(_translate("DrugUpdatingWindow", "Load info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrugUpdatingWindow = QtWidgets.QDialog()
    ui = Ui_DrugUpdatingWindow()
    ui.setupUi(DrugUpdatingWindow)
    DrugUpdatingWindow.show()
    sys.exit(app.exec_())
