# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/DrugAddingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrugAddingWindow(object):
    def setupUi(self, DrugAddingWindow):
        DrugAddingWindow.setObjectName("DrugAddingWindow")
        DrugAddingWindow.setEnabled(True)
        DrugAddingWindow.resize(580, 410)
        DrugAddingWindow.setMinimumSize(QtCore.QSize(580, 410))
        DrugAddingWindow.setMaximumSize(QtCore.QSize(580, 410))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DrugAddingWindow.setWindowIcon(icon)
        DrugAddingWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.add_drug_btn = QtWidgets.QPushButton(DrugAddingWindow)
        self.add_drug_btn.setGeometry(QtCore.QRect(470, 370, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_drug_btn.setFont(font)
        self.add_drug_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_drug_btn.setObjectName("add_drug_btn")
        self.inputline_drug_atc = QtWidgets.QLineEdit(DrugAddingWindow)
        self.inputline_drug_atc.setGeometry(QtCore.QRect(340, 10, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputline_drug_atc.setFont(font)
        self.inputline_drug_atc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.inputline_drug_atc.setInputMask("")
        self.inputline_drug_atc.setMaxLength(7)
        self.inputline_drug_atc.setObjectName("inputline_drug_atc")
        self.inputline_drug_name = QtWidgets.QLineEdit(DrugAddingWindow)
        self.inputline_drug_name.setGeometry(QtCore.QRect(20, 10, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputline_drug_name.setFont(font)
        self.inputline_drug_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.inputline_drug_name.setMaxLength(200)
        self.inputline_drug_name.setObjectName("inputline_drug_name")
        self.manufacturerComboBox = QtWidgets.QComboBox(DrugAddingWindow)
        self.manufacturerComboBox.setGeometry(QtCore.QRect(20, 60, 541, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.manufacturerComboBox.setFont(font)
        self.manufacturerComboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.manufacturerComboBox.setCurrentText("")
        self.manufacturerComboBox.setObjectName("manufacturerComboBox")
        self.label = QtWidgets.QLabel(DrugAddingWindow)
        self.label.setGeometry(QtCore.QRect(20, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DrugAddingWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.supplierComboBox = QtWidgets.QComboBox(DrugAddingWindow)
        self.supplierComboBox.setGeometry(QtCore.QRect(20, 140, 541, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.supplierComboBox.setFont(font)
        self.supplierComboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.supplierComboBox.setCurrentText("")
        self.supplierComboBox.setObjectName("supplierComboBox")
        self.inputline_drug_description = QtWidgets.QPlainTextEdit(DrugAddingWindow)
        self.inputline_drug_description.setGeometry(QtCore.QRect(20, 180, 541, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputline_drug_description.setFont(font)
        self.inputline_drug_description.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.inputline_drug_description.setMaximumBlockCount(0)
        self.inputline_drug_description.setBackgroundVisible(False)
        self.inputline_drug_description.setObjectName("inputline_drug_description")
        self.label_3 = QtWidgets.QLabel(DrugAddingWindow)
        self.label_3.setGeometry(QtCore.QRect(420, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.quantity_spnbox = QtWidgets.QSpinBox(DrugAddingWindow)
        self.quantity_spnbox.setGeometry(QtCore.QRect(500, 10, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantity_spnbox.setFont(font)
        self.quantity_spnbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.quantity_spnbox.setMaximum(9999)
        self.quantity_spnbox.setObjectName("quantity_spnbox")
        self.manufacturer_is_supplier_checkbox = QtWidgets.QCheckBox(DrugAddingWindow)
        self.manufacturer_is_supplier_checkbox.setGeometry(QtCore.QRect(10, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.manufacturer_is_supplier_checkbox.setFont(font)
        self.manufacturer_is_supplier_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.manufacturer_is_supplier_checkbox.setStyleSheet("color: rgb(255, 255, 255);")
        self.manufacturer_is_supplier_checkbox.setChecked(False)
        self.manufacturer_is_supplier_checkbox.setObjectName("manufacturer_is_supplier_checkbox")

        self.retranslateUi(DrugAddingWindow)
        QtCore.QMetaObject.connectSlotsByName(DrugAddingWindow)

    def retranslateUi(self, DrugAddingWindow):
        _translate = QtCore.QCoreApplication.translate
        DrugAddingWindow.setWindowTitle(_translate("DrugAddingWindow", "Drug adding"))
        self.add_drug_btn.setText(_translate("DrugAddingWindow", "Add drug"))
        self.inputline_drug_atc.setPlaceholderText(_translate("DrugAddingWindow", "atc code"))
        self.inputline_drug_name.setPlaceholderText(_translate("DrugAddingWindow", "drug name"))
        self.manufacturerComboBox.setPlaceholderText(_translate("DrugAddingWindow", "manufacturer"))
        self.label.setText(_translate("DrugAddingWindow", "Manufacturer"))
        self.label_2.setText(_translate("DrugAddingWindow", "Supplier"))
        self.supplierComboBox.setPlaceholderText(_translate("DrugAddingWindow", "supplier"))
        self.inputline_drug_description.setPlaceholderText(_translate("DrugAddingWindow", "description"))
        self.label_3.setText(_translate("DrugAddingWindow", "Quantity"))
        self.manufacturer_is_supplier_checkbox.setText(_translate("DrugAddingWindow", "Supplier is manufacturer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrugAddingWindow = QtWidgets.QDialog()
    ui = Ui_DrugAddingWindow()
    ui.setupUi(DrugAddingWindow)
    DrugAddingWindow.show()
    sys.exit(app.exec_())
