# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/DelDrugWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrugDelWindow(object):
    def setupUi(self, DrugDelWindow):
        DrugDelWindow.setObjectName("DrugDelWindow")
        DrugDelWindow.resize(350, 80)
        self.inputline_drug_name = QtWidgets.QLineEdit(DrugDelWindow)
        self.inputline_drug_name.setGeometry(QtCore.QRect(20, 10, 311, 22))
        self.inputline_drug_name.setObjectName("inputline_drug_name")
        self.del_drug_btn = QtWidgets.QPushButton(DrugDelWindow)
        self.del_drug_btn.setGeometry(QtCore.QRect(120, 40, 93, 28))
        self.del_drug_btn.setObjectName("del_drug_btn")

        self.retranslateUi(DrugDelWindow)
        QtCore.QMetaObject.connectSlotsByName(DrugDelWindow)

    def retranslateUi(self, DrugDelWindow):
        _translate = QtCore.QCoreApplication.translate
        DrugDelWindow.setWindowTitle(_translate("DrugDelWindow", "Delete Drug"))
        self.inputline_drug_name.setPlaceholderText(_translate("DrugDelWindow", "drug name"))
        self.del_drug_btn.setText(_translate("DrugDelWindow", "Delete drug"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrugDelWindow = QtWidgets.QDialog()
    ui = Ui_DrugDelWindow()
    ui.setupUi(DrugDelWindow)
    DrugDelWindow.show()
    sys.exit(app.exec_())
