# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/IssueLogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IssueLogWindow(object):
    def setupUi(self, IssueLogWindow):
        IssueLogWindow.setObjectName("IssueLogWindow")
        IssueLogWindow.resize(1280, 610)
        IssueLogWindow.setMinimumSize(QtCore.QSize(1280, 610))
        IssueLogWindow.setMaximumSize(QtCore.QSize(1280, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IssueLogWindow.setWindowIcon(icon)
        IssueLogWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.tableWidget = QtWidgets.QTableWidget(IssueLogWindow)
        self.tableWidget.setGeometry(QtCore.QRect(0, 90, 1280, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.refresh_btn = QtWidgets.QPushButton(IssueLogWindow)
        self.refresh_btn.setGeometry(QtCore.QRect(898, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.refresh_btn.setObjectName("refresh_btn")
        self.search_btn = QtWidgets.QPushButton(IssueLogWindow)
        self.search_btn.setEnabled(True)
        self.search_btn.setGeometry(QtCore.QRect(790, 10, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.search_drug_fld = QtWidgets.QLineEdit(IssueLogWindow)
        self.search_drug_fld.setGeometry(QtCore.QRect(370, 10, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_drug_fld.setFont(font)
        self.search_drug_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.search_drug_fld.setMaxLength(200)
        self.search_drug_fld.setObjectName("search_drug_fld")
        self.datetime_editor_from = QtWidgets.QDateTimeEdit(IssueLogWindow)
        self.datetime_editor_from.setGeometry(QtCore.QRect(60, 10, 194, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.datetime_editor_from.setFont(font)
        self.datetime_editor_from.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.datetime_editor_from.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 9, 14), QtCore.QTime(0, 0, 0)))
        self.datetime_editor_from.setObjectName("datetime_editor_from")
        self.datetime_editor_to = QtWidgets.QDateTimeEdit(IssueLogWindow)
        self.datetime_editor_to.setGeometry(QtCore.QRect(60, 40, 194, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.datetime_editor_to.setFont(font)
        self.datetime_editor_to.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.datetime_editor_to.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 12, 30), QtCore.QTime(0, 0, 0)))
        self.datetime_editor_to.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 9, 14), QtCore.QTime(0, 0, 0)))
        self.datetime_editor_to.setObjectName("datetime_editor_to")
        self.label = QtWidgets.QLabel(IssueLogWindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(IssueLogWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.medic_fname_fld = QtWidgets.QLineEdit(IssueLogWindow)
        self.medic_fname_fld.setGeometry(QtCore.QRect(580, 50, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medic_fname_fld.setFont(font)
        self.medic_fname_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.medic_fname_fld.setMaxLength(50)
        self.medic_fname_fld.setObjectName("medic_fname_fld")
        self.medic_lname_fld = QtWidgets.QLineEdit(IssueLogWindow)
        self.medic_lname_fld.setGeometry(QtCore.QRect(370, 50, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medic_lname_fld.setFont(font)
        self.medic_lname_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.medic_lname_fld.setMaxLength(50)
        self.medic_lname_fld.setObjectName("medic_lname_fld")
        self.medic_patronymic_fld = QtWidgets.QLineEdit(IssueLogWindow)
        self.medic_patronymic_fld.setGeometry(QtCore.QRect(790, 50, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medic_patronymic_fld.setFont(font)
        self.medic_patronymic_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.medic_patronymic_fld.setMaxLength(50)
        self.medic_patronymic_fld.setObjectName("medic_patronymic_fld")

        self.retranslateUi(IssueLogWindow)
        QtCore.QMetaObject.connectSlotsByName(IssueLogWindow)

    def retranslateUi(self, IssueLogWindow):
        _translate = QtCore.QCoreApplication.translate
        IssueLogWindow.setWindowTitle(_translate("IssueLogWindow", "Issue log"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("IssueLogWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("IssueLogWindow", "Drug"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("IssueLogWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("IssueLogWindow", "Medic name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("IssueLogWindow", "Medic rank"))
        self.refresh_btn.setText(_translate("IssueLogWindow", "Refresh"))
        self.search_btn.setText(_translate("IssueLogWindow", "Search"))
        self.search_drug_fld.setPlaceholderText(_translate("IssueLogWindow", "Drug name"))
        self.datetime_editor_from.setDisplayFormat(_translate("IssueLogWindow", "dd-MM-yyyy HH:mm"))
        self.datetime_editor_to.setDisplayFormat(_translate("IssueLogWindow", "dd-MM-yyyy HH:mm"))
        self.label.setText(_translate("IssueLogWindow", "From"))
        self.label_2.setText(_translate("IssueLogWindow", "To"))
        self.medic_fname_fld.setPlaceholderText(_translate("IssueLogWindow", "Medic first name"))
        self.medic_lname_fld.setPlaceholderText(_translate("IssueLogWindow", "Medic last name"))
        self.medic_patronymic_fld.setPlaceholderText(_translate("IssueLogWindow", "Medic patronymic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IssueLogWindow = QtWidgets.QDialog()
    ui = Ui_IssueLogWindow()
    ui.setupUi(IssueLogWindow)
    IssueLogWindow.show()
    sys.exit(app.exec_())
