# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setWindowModality(QtCore.Qt.NonModal)
        LoginWindow.resize(350, 260)
        LoginWindow.setMinimumSize(QtCore.QSize(350, 260))
        LoginWindow.setMaximumSize(QtCore.QSize(350, 260))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.username_fld = QtWidgets.QLineEdit(LoginWindow)
        self.username_fld.setGeometry(QtCore.QRect(60, 70, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_fld.setFont(font)
        self.username_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(8, 8, 8);\n"
"border-radius: 15px;")
        self.username_fld.setAlignment(QtCore.Qt.AlignCenter)
        self.username_fld.setObjectName("username_fld")
        self.dbname_fld = QtWidgets.QLineEdit(LoginWindow)
        self.dbname_fld.setGeometry(QtCore.QRect(60, 31, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dbname_fld.setFont(font)
        self.dbname_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(8, 8, 8);\n"
"border-radius: 15px;")
        self.dbname_fld.setMaxLength(50)
        self.dbname_fld.setAlignment(QtCore.Qt.AlignCenter)
        self.dbname_fld.setObjectName("dbname_fld")
        self.password_fld = QtWidgets.QLineEdit(LoginWindow)
        self.password_fld.setGeometry(QtCore.QRect(60, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_fld.setFont(font)
        self.password_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(8, 8, 8);\n"
"border-radius: 15px;")
        self.password_fld.setMaxLength(16)
        self.password_fld.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_fld.setAlignment(QtCore.Qt.AlignCenter)
        self.password_fld.setDragEnabled(False)
        self.password_fld.setReadOnly(False)
        self.password_fld.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.password_fld.setObjectName("password_fld")
        self.permit_btn = QtWidgets.QPushButton(LoginWindow)
        self.permit_btn.setGeometry(QtCore.QRect(120, 200, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.permit_btn.setFont(font)
        self.permit_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.permit_btn.setObjectName("permit_btn")
        self.host_fld = QtWidgets.QLineEdit(LoginWindow)
        self.host_fld.setGeometry(QtCore.QRect(60, 150, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.host_fld.setFont(font)
        self.host_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(8, 8, 8);\n"
"border-radius: 15px;")
        self.host_fld.setMaxLength(20)
        self.host_fld.setAlignment(QtCore.Qt.AlignCenter)
        self.host_fld.setObjectName("host_fld")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login Window"))
        self.username_fld.setText(_translate("LoginWindow", "pharmacy_worker"))
        self.username_fld.setPlaceholderText(_translate("LoginWindow", "Username"))
        self.dbname_fld.setText(_translate("LoginWindow", "pharmacy_db"))
        self.dbname_fld.setPlaceholderText(_translate("LoginWindow", "Database name"))
        self.password_fld.setText(_translate("LoginWindow", "standard"))
        self.password_fld.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.permit_btn.setText(_translate("LoginWindow", "Permit"))
        self.host_fld.setText(_translate("LoginWindow", "localhost"))
        self.host_fld.setPlaceholderText(_translate("LoginWindow", "Host:port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QDialog()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
