# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 525)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(830, 525))
        MainWindow.setMaximumSize(QtCore.QSize(830, 525))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drugs_label = QtWidgets.QLabel(self.centralwidget)
        self.drugs_label.setGeometry(QtCore.QRect(30, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.drugs_label.setFont(font)
        self.drugs_label.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.drugs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drugs_label.setObjectName("drugs_label")
        self.add_drugs_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_drugs_btn.setGeometry(QtCore.QRect(30, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_drugs_btn.setFont(font)
        self.add_drugs_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_drugs_btn.setObjectName("add_drugs_btn")
        self.manage_drugs_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manage_drugs_btn.setGeometry(QtCore.QRect(30, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.manage_drugs_btn.setFont(font)
        self.manage_drugs_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.manage_drugs_btn.setObjectName("manage_drugs_btn")
        self.add_manufacturers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_manufacturers_btn.setGeometry(QtCore.QRect(30, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_manufacturers_btn.setFont(font)
        self.add_manufacturers_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_manufacturers_btn.setObjectName("add_manufacturers_btn")
        self.manufacturers_label = QtWidgets.QLabel(self.centralwidget)
        self.manufacturers_label.setGeometry(QtCore.QRect(30, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.manufacturers_label.setFont(font)
        self.manufacturers_label.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.manufacturers_label.setAlignment(QtCore.Qt.AlignCenter)
        self.manufacturers_label.setObjectName("manufacturers_label")
        self.manage_manufacturers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manage_manufacturers_btn.setGeometry(QtCore.QRect(30, 390, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.manage_manufacturers_btn.setFont(font)
        self.manage_manufacturers_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.manage_manufacturers_btn.setObjectName("manage_manufacturers_btn")
        self.manage_suppliers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manage_suppliers_btn.setGeometry(QtCore.QRect(190, 390, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.manage_suppliers_btn.setFont(font)
        self.manage_suppliers_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.manage_suppliers_btn.setObjectName("manage_suppliers_btn")
        self.suppliers_label = QtWidgets.QLabel(self.centralwidget)
        self.suppliers_label.setGeometry(QtCore.QRect(190, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.suppliers_label.setFont(font)
        self.suppliers_label.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.suppliers_label.setAlignment(QtCore.Qt.AlignCenter)
        self.suppliers_label.setObjectName("suppliers_label")
        self.add_suppliers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_suppliers_btn.setGeometry(QtCore.QRect(190, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_suppliers_btn.setFont(font)
        self.add_suppliers_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_suppliers_btn.setObjectName("add_suppliers_btn")
        self.issue_log_btn = QtWidgets.QPushButton(self.centralwidget)
        self.issue_log_btn.setGeometry(QtCore.QRect(100, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.issue_log_btn.setFont(font)
        self.issue_log_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.issue_log_btn.setObjectName("issue_log_btn")
        self.DogLabel = QtWidgets.QLabel(self.centralwidget)
        self.DogLabel.setGeometry(QtCore.QRect(560, 260, 201, 201))
        self.DogLabel.setStyleSheet("background-color: rgb(0, 0, 53);")
        self.DogLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DogLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DogLabel.setText("")
        self.DogLabel.setPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../dog.gif"))
        self.DogLabel.setScaledContents(True)
        self.DogLabel.setObjectName("DogLabel")
        self.nyan_dog_label = QtWidgets.QLabel(self.centralwidget)
        self.nyan_dog_label.setGeometry(QtCore.QRect(100, 30, 701, 171))
        self.nyan_dog_label.setText("")
        self.nyan_dog_label.setPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../nyan_dog.gif"))
        self.nyan_dog_label.setScaledContents(False)
        self.nyan_dog_label.setObjectName("nyan_dog_label")
        self.dogbackground = QtWidgets.QLabel(self.centralwidget)
        self.dogbackground.setGeometry(QtCore.QRect(480, 240, 331, 241))
        self.dogbackground.setStyleSheet("background-color: rgb(0, 0, 53);\n"
"border-radius: 150px 80px;")
        self.dogbackground.setText("")
        self.dogbackground.setObjectName("dogbackground")
        self.dogbackground_2 = QtWidgets.QLabel(self.centralwidget)
        self.dogbackground_2.setGeometry(QtCore.QRect(410, 210, 71, 71))
        self.dogbackground_2.setStyleSheet("background-color: rgb(0, 0, 53);\n"
"border-radius: 30px 30px;")
        self.dogbackground_2.setText("")
        self.dogbackground_2.setObjectName("dogbackground_2")
        self.dogbackground_3 = QtWidgets.QLabel(self.centralwidget)
        self.dogbackground_3.setGeometry(QtCore.QRect(500, 200, 41, 41))
        self.dogbackground_3.setStyleSheet("background-color: rgb(0, 0, 53);\n"
"border-radius: 15px 15px;")
        self.dogbackground_3.setText("")
        self.dogbackground_3.setObjectName("dogbackground_3")
        self.manage_prohihbition_list_btn = QtWidgets.QPushButton(self.centralwidget)
        self.manage_prohihbition_list_btn.setGeometry(QtCore.QRect(190, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.manage_prohihbition_list_btn.setFont(font)
        self.manage_prohihbition_list_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.manage_prohihbition_list_btn.setObjectName("manage_prohihbition_list_btn")
        self.prohibited_label = QtWidgets.QLabel(self.centralwidget)
        self.prohibited_label.setGeometry(QtCore.QRect(190, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.prohibited_label.setFont(font)
        self.prohibited_label.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.prohibited_label.setAlignment(QtCore.Qt.AlignCenter)
        self.prohibited_label.setObjectName("prohibited_label")
        self.add_prohibition_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_prohibition_btn.setGeometry(QtCore.QRect(190, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_prohibition_btn.setFont(font)
        self.add_prohibition_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 110, 175);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_prohibition_btn.setObjectName("add_prohibition_btn")
        self.delivery_log_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delivery_log_btn.setGeometry(QtCore.QRect(100, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delivery_log_btn.setFont(font)
        self.delivery_log_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.delivery_log_btn.setObjectName("delivery_log_btn")
        self.dogbackground.raise_()
        self.nyan_dog_label.raise_()
        self.drugs_label.raise_()
        self.add_drugs_btn.raise_()
        self.manage_drugs_btn.raise_()
        self.add_manufacturers_btn.raise_()
        self.manufacturers_label.raise_()
        self.manage_manufacturers_btn.raise_()
        self.manage_suppliers_btn.raise_()
        self.suppliers_label.raise_()
        self.add_suppliers_btn.raise_()
        self.issue_log_btn.raise_()
        self.DogLabel.raise_()
        self.dogbackground_2.raise_()
        self.dogbackground_3.raise_()
        self.manage_prohihbition_list_btn.raise_()
        self.prohibited_label.raise_()
        self.add_prohibition_btn.raise_()
        self.delivery_log_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Window"))
        self.drugs_label.setText(_translate("MainWindow", "Drugs"))
        self.add_drugs_btn.setText(_translate("MainWindow", "Add"))
        self.manage_drugs_btn.setText(_translate("MainWindow", "Manage"))
        self.add_manufacturers_btn.setText(_translate("MainWindow", "Add"))
        self.manufacturers_label.setText(_translate("MainWindow", "Manufacturers"))
        self.manage_manufacturers_btn.setText(_translate("MainWindow", "Manage"))
        self.manage_suppliers_btn.setText(_translate("MainWindow", "Manage"))
        self.suppliers_label.setText(_translate("MainWindow", "Suppliers"))
        self.add_suppliers_btn.setText(_translate("MainWindow", "Add"))
        self.issue_log_btn.setText(_translate("MainWindow", "Issue log"))
        self.manage_prohihbition_list_btn.setText(_translate("MainWindow", "Manage"))
        self.prohibited_label.setText(_translate("MainWindow", "Prohibition list"))
        self.add_prohibition_btn.setText(_translate("MainWindow", "Add"))
        self.delivery_log_btn.setText(_translate("MainWindow", "Delivery log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
