# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/ManageSuppliersWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageSuppliersWindow(object):
    def setupUi(self, ManageSuppliersWindow):
        ManageSuppliersWindow.setObjectName("ManageSuppliersWindow")
        ManageSuppliersWindow.resize(990, 610)
        ManageSuppliersWindow.setMinimumSize(QtCore.QSize(990, 610))
        ManageSuppliersWindow.setMaximumSize(QtCore.QSize(1280, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ManageSuppliersWindow.setWindowIcon(icon)
        ManageSuppliersWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.tableWidget = QtWidgets.QTableWidget(ManageSuppliersWindow)
        self.tableWidget.setGeometry(QtCore.QRect(0, 90, 990, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.refresh_btn = QtWidgets.QPushButton(ManageSuppliersWindow)
        self.refresh_btn.setGeometry(QtCore.QRect(878, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.refresh_btn.setObjectName("refresh_btn")
        self.search_btn = QtWidgets.QPushButton(ManageSuppliersWindow)
        self.search_btn.setEnabled(True)
        self.search_btn.setGeometry(QtCore.QRect(770, 10, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.search_supplier_fld = QtWidgets.QLineEdit(ManageSuppliersWindow)
        self.search_supplier_fld.setGeometry(QtCore.QRect(280, 10, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_supplier_fld.setFont(font)
        self.search_supplier_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.search_supplier_fld.setMaxLength(200)
        self.search_supplier_fld.setObjectName("search_supplier_fld")
        self.add_supplier_btn = QtWidgets.QPushButton(ManageSuppliersWindow)
        self.add_supplier_btn.setGeometry(QtCore.QRect(20, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_supplier_btn.setFont(font)
        self.add_supplier_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_supplier_btn.setObjectName("add_supplier_btn")
        self.search_country_fld = QtWidgets.QLineEdit(ManageSuppliersWindow)
        self.search_country_fld.setGeometry(QtCore.QRect(280, 50, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_country_fld.setFont(font)
        self.search_country_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.search_country_fld.setMaxLength(200)
        self.search_country_fld.setObjectName("search_country_fld")
        self.update_supplier_btn = QtWidgets.QPushButton(ManageSuppliersWindow)
        self.update_supplier_btn.setGeometry(QtCore.QRect(20, 50, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update_supplier_btn.setFont(font)
        self.update_supplier_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.update_supplier_btn.setObjectName("update_supplier_btn")

        self.retranslateUi(ManageSuppliersWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageSuppliersWindow)

    def retranslateUi(self, ManageSuppliersWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageSuppliersWindow.setWindowTitle(_translate("ManageSuppliersWindow", "Manage Suppliers"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ManageSuppliersWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ManageSuppliersWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ManageSuppliersWindow", "Country"))
        self.refresh_btn.setText(_translate("ManageSuppliersWindow", "Refresh"))
        self.search_btn.setText(_translate("ManageSuppliersWindow", "Search"))
        self.search_supplier_fld.setPlaceholderText(_translate("ManageSuppliersWindow", "Supplier name"))
        self.add_supplier_btn.setText(_translate("ManageSuppliersWindow", "Add"))
        self.search_country_fld.setPlaceholderText(_translate("ManageSuppliersWindow", "Country"))
        self.update_supplier_btn.setText(_translate("ManageSuppliersWindow", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageSuppliersWindow = QtWidgets.QDialog()
    ui = Ui_ManageSuppliersWindow()
    ui.setupUi(ManageSuppliersWindow)
    ManageSuppliersWindow.show()
    sys.exit(app.exec_())
