# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/ManageProhibitionsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageProhibitionsWindow(object):
    def setupUi(self, ManageProhibitionsWindow):
        ManageProhibitionsWindow.setObjectName("ManageProhibitionsWindow")
        ManageProhibitionsWindow.resize(1280, 610)
        ManageProhibitionsWindow.setMinimumSize(QtCore.QSize(1280, 610))
        ManageProhibitionsWindow.setMaximumSize(QtCore.QSize(1280, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ManageProhibitionsWindow.setWindowIcon(icon)
        ManageProhibitionsWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.tableWidget = QtWidgets.QTableWidget(ManageProhibitionsWindow)
        self.tableWidget.setGeometry(QtCore.QRect(0, 90, 1280, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.refresh_btn = QtWidgets.QPushButton(ManageProhibitionsWindow)
        self.refresh_btn.setGeometry(QtCore.QRect(898, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.refresh_btn.setObjectName("refresh_btn")
        self.search_btn = QtWidgets.QPushButton(ManageProhibitionsWindow)
        self.search_btn.setEnabled(True)
        self.search_btn.setGeometry(QtCore.QRect(790, 10, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.search_drug_fld = QtWidgets.QLineEdit(ManageProhibitionsWindow)
        self.search_drug_fld.setGeometry(QtCore.QRect(280, 10, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_drug_fld.setFont(font)
        self.search_drug_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.search_drug_fld.setMaxLength(200)
        self.search_drug_fld.setObjectName("search_drug_fld")
        self.rank_cbox = QtWidgets.QComboBox(ManageProhibitionsWindow)
        self.rank_cbox.setGeometry(QtCore.QRect(380, 50, 401, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rank_cbox.setFont(font)
        self.rank_cbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.rank_cbox.setCurrentText("")
        self.rank_cbox.setObjectName("rank_cbox")
        self.label = QtWidgets.QLabel(ManageProhibitionsWindow)
        self.label.setGeometry(QtCore.QRect(280, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.add_prohibition_btn = QtWidgets.QPushButton(ManageProhibitionsWindow)
        self.add_prohibition_btn.setGeometry(QtCore.QRect(20, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_prohibition_btn.setFont(font)
        self.add_prohibition_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_prohibition_btn.setObjectName("add_prohibition_btn")
        self.delete_prohibition_btn = QtWidgets.QPushButton(ManageProhibitionsWindow)
        self.delete_prohibition_btn.setGeometry(QtCore.QRect(120, 10, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_prohibition_btn.setFont(font)
        self.delete_prohibition_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.delete_prohibition_btn.setObjectName("delete_prohibition_btn")

        self.retranslateUi(ManageProhibitionsWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageProhibitionsWindow)

    def retranslateUi(self, ManageProhibitionsWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageProhibitionsWindow.setWindowTitle(_translate("ManageProhibitionsWindow", "Manage Prohibitions"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ManageProhibitionsWindow", "Prohibition ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ManageProhibitionsWindow", "Drug"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ManageProhibitionsWindow", "Medic rank"))
        self.refresh_btn.setText(_translate("ManageProhibitionsWindow", "Refresh"))
        self.search_btn.setText(_translate("ManageProhibitionsWindow", "Search"))
        self.search_drug_fld.setPlaceholderText(_translate("ManageProhibitionsWindow", "Drug name"))
        self.rank_cbox.setPlaceholderText(_translate("ManageProhibitionsWindow", "rank"))
        self.label.setText(_translate("ManageProhibitionsWindow", "Medic rank"))
        self.add_prohibition_btn.setText(_translate("ManageProhibitionsWindow", "Add"))
        self.delete_prohibition_btn.setText(_translate("ManageProhibitionsWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageProhibitionsWindow = QtWidgets.QDialog()
    ui = Ui_ManageProhibitionsWindow()
    ui.setupUi(ManageProhibitionsWindow)
    ManageProhibitionsWindow.show()
    sys.exit(app.exec_())
