# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kaireen/Documents/CPr/Application/windows_ui/SupplierAddingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SupplierAddingWindow(object):
    def setupUi(self, SupplierAddingWindow):
        SupplierAddingWindow.setObjectName("SupplierAddingWindow")
        SupplierAddingWindow.setEnabled(True)
        SupplierAddingWindow.resize(550, 320)
        SupplierAddingWindow.setMinimumSize(QtCore.QSize(550, 320))
        SupplierAddingWindow.setMaximumSize(QtCore.QSize(550, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/kaireen/Documents/CPr/Application/windows_ui/../media/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SupplierAddingWindow.setWindowIcon(icon)
        SupplierAddingWindow.setStyleSheet("background-color: rgb(32, 178, 170);")
        self.add_supplier_btn = QtWidgets.QPushButton(SupplierAddingWindow)
        self.add_supplier_btn.setGeometry(QtCore.QRect(440, 280, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_supplier_btn.setFont(font)
        self.add_supplier_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 172, 172);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 205, 255);\n"
"}")
        self.add_supplier_btn.setObjectName("add_supplier_btn")
        self.supplier_name_fld = QtWidgets.QLineEdit(SupplierAddingWindow)
        self.supplier_name_fld.setGeometry(QtCore.QRect(20, 10, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.supplier_name_fld.setFont(font)
        self.supplier_name_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.supplier_name_fld.setMaxLength(200)
        self.supplier_name_fld.setObjectName("supplier_name_fld")
        self.contact_info_fld = QtWidgets.QPlainTextEdit(SupplierAddingWindow)
        self.contact_info_fld.setGeometry(QtCore.QRect(20, 80, 511, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contact_info_fld.setFont(font)
        self.contact_info_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.contact_info_fld.setMaximumBlockCount(0)
        self.contact_info_fld.setBackgroundVisible(False)
        self.contact_info_fld.setObjectName("contact_info_fld")
        self.country_fld = QtWidgets.QLineEdit(SupplierAddingWindow)
        self.country_fld.setGeometry(QtCore.QRect(20, 40, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.country_fld.setFont(font)
        self.country_fld.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 15px;")
        self.country_fld.setMaxLength(200)
        self.country_fld.setObjectName("country_fld")

        self.retranslateUi(SupplierAddingWindow)
        QtCore.QMetaObject.connectSlotsByName(SupplierAddingWindow)

    def retranslateUi(self, SupplierAddingWindow):
        _translate = QtCore.QCoreApplication.translate
        SupplierAddingWindow.setWindowTitle(_translate("SupplierAddingWindow", "Supplier Adding"))
        self.add_supplier_btn.setText(_translate("SupplierAddingWindow", "Add"))
        self.supplier_name_fld.setPlaceholderText(_translate("SupplierAddingWindow", "Supplier name"))
        self.contact_info_fld.setPlaceholderText(_translate("SupplierAddingWindow", "Contact info"))
        self.country_fld.setPlaceholderText(_translate("SupplierAddingWindow", "Country"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SupplierAddingWindow = QtWidgets.QDialog()
    ui = Ui_SupplierAddingWindow()
    ui.setupUi(SupplierAddingWindow)
    SupplierAddingWindow.show()
    sys.exit(app.exec_())
